import './globals.css'
import { Inter } from 'next/font/google'
// import { Analytics } from '@vercel/analytics/next';
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Harshita Poojary Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: "/images/favicon.ico", // Ensure the path matches your favicon
  },

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* GA script loader */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=G-WZBBLBD79R`}
          strategy="afterInteractive"
        />
        {/* GA init */}
        <Script id="ga-gtag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            window.gtag = gtag;
            gtag('js', new Date());
            gtag('config', 'G-WZBBLBD79R');
          `}
        </Script>
      </head>
      <body className={inter.className}>{children}
      {/* <Analytics /> */}
      </body>
    </html>
  )
}
