import './globals.css'
import { Inter } from 'next/font/google'
// import { Analytics } from '@vercel/analytics/next';
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

const withBase = (p) => `${process.env.NEXT_PUBLIC_BASE_PATH || ''}${p}`

export const metadata = {
  title: 'Harshita Poojary Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: withBase('/images/favicon.ico'), // Ensure the path matches your favicon
  },
}

const GA_ID = process.env.NEXT_PUBLIC_GA_ID || "G-WZBBLBD79R";
const isProd = process.env.NODE_ENV === "production";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-WZBBLBD79R"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-WZBBLBD79R');
          `}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}