name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # deploy when pushing to master

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_ENV: production
  NEXT_PUBLIC_GA_ID: G-WZBBLBD79R
  NEXT_PUBLIC_BASE_PATH: /harshitapoojary.github.io
   
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_PUBLIC_GA_ID: G-WZBBLBD79R
      NEXT_PUBLIC_BASE_PATH: /harshitapoojary.github.io
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build           # creates ./out thanks to output:"export"
      - run: touch out/.nojekyll     # ensure GH Pages serves _next assets
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
