name: Deploy Next.js site to Pages

on:
  push:
    branches: [ master ]      # or master if that's your default
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Keep the step but WITHOUT the 'with: static_site_generator'
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build        # creates ./out (because output: "export")

      - run: touch out/.nojekyll  # allow _next/* on Pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
